name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.2
        with: 
          node-version: 16.13.2

      - name: Install Mocha
        run: |
          cd src;
          npm install -g mocha;
          npm install

      - name: Execute Tests
        run: mocha src/test/convert.js
        
        
      - name: Docker Image
        uses: docker/build-push-action@v5.3.0
        with: 
          context: src 
          file: src/Dockerfile
          push: true
          tags: |
            leonardoapiovezan/conversao-temperatura:v1
            leonardoapiovezan/conversao-temperatura:latest
          
